name: Flutter Android Build

on:
  push:
    branches: ["main", "master", "rony"]
  pull_request:
    branches: ["main", "master"]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1. Setup Java
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      # 2. Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      # 3. Install Libraries
      - name: Install Dependencies
        run: flutter pub get

      # 4. Analyze Code (Tetap lanjut meski ada warning)
      - name: Analyze Code
        continue-on-error: true
        run: flutter analyze

      # 5. Build APK (Debug Version)
      # FIX: Tambahkan _JAVA_OPTIONS untuk menaikkan RAM ke 4GB (Max Heap)
      # Ini solusi untuk error "Java heap space"
      - name: Build Android APK
        env:
          _JAVA_OPTIONS: "-Xmx4096m"
        run: flutter build apk --debug

      # 6. Upload APK ke GitHub
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: bhinnekapay-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
